# Generated by Django 2.2.2 on 2020-01-18 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('age', models.CharField(choices=[('0', 'All'), ('21', 'Adults'), ('16', 'Teenagers'), ('6', 'Kids')], max_length=2)),
                ('kind', models.CharField(choices=[('ScI', 'Science-Fiction'), ('R', 'Romance'), ('C', 'Comedy'), ('D', 'Drama'), ('T', 'Thriller'), ('H', 'Horror'), ('F', 'Fantasty')], max_length=3)),
                ('price', models.FloatField()),
                ('date', models.DateField()),
                ('max_seats', models.IntegerField(default=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=1)),
                ('number', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Movies')),
            ],
        ),
        migrations.CreateModel(
            name='Reserve_seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=1)),
                ('number', models.IntegerField()),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Movies')),
            ],
        ),
    ]
