# Generated by Django 2.2.2 on 2020-02-01 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('age', models.CharField(choices=[('0', 'All'), ('21', 'Adults'), ('16', 'Teenagers'), ('6', 'Kids')], max_length=2)),
                ('kind', models.CharField(choices=[('ScI', 'Science-Fiction'), ('D', 'Drama'), ('H', 'Horror'), ('R', 'Romance'), ('F', 'Fantasty'), ('T', 'Thriller'), ('C', 'Comedy')], max_length=3)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Seats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('row', models.CharField(max_length=1)),
                ('number', models.IntegerField()),
                ('ordered', models.DateTimeField(blank=True, default='2020-02-01 22:29', null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reservations', models.ManyToManyField(to='main.User_Seats')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.ManyToManyField(to='main.Dates')),
                ('main_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Movies')),
                ('time', models.ManyToManyField(to='main.Hours')),
            ],
        ),
        migrations.AddField(
            model_name='dates',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Movies'),
        ),
    ]
