# Generated by Django 2.2.2 on 2020-02-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='image',
            field=models.ImageField(blank=True, upload_to='movie_images'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='age',
            field=models.CharField(choices=[('16', 'Teenagers'), ('0', 'All'), ('21', 'Adults'), ('6', 'Kids')], max_length=2),
        ),
        migrations.AlterField(
            model_name='movies',
            name='kind',
            field=models.CharField(choices=[('ScI', 'Science-Fiction'), ('R', 'Romance'), ('H', 'Horror'), ('C', 'Comedy'), ('F', 'Fantasty'), ('T', 'Thriller'), ('D', 'Drama')], max_length=3),
        ),
        migrations.AlterField(
            model_name='user_seats',
            name='ordered',
            field=models.DateTimeField(blank=True, default='2020-02-07 13:42', null=True),
        ),
    ]
