# Generated by Django 2.2.2 on 2020-01-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='age',
            field=models.CharField(choices=[('21', 'Adults'), ('16', 'Teenagers'), ('6', 'Kids'), ('0', 'All')], max_length=2),
        ),
        migrations.AlterField(
            model_name='movies',
            name='kind',
            field=models.CharField(choices=[('F', 'Fantasty'), ('C', 'Comedy'), ('D', 'Drama'), ('ScI', 'Science-Fiction'), ('R', 'Romance'), ('H', 'Horror'), ('T', 'Thriller')], max_length=3),
        ),
        migrations.DeleteModel(
            name='Reserve_seat',
        ),
    ]
