# Generated by Django 2.2.2 on 2020-02-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200207_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='cew',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='age',
            field=models.CharField(choices=[('6', 'Kids'), ('21', 'Adults'), ('0', 'All'), ('16', 'Teenagers')], max_length=2),
        ),
        migrations.AlterField(
            model_name='movies',
            name='kind',
            field=models.CharField(choices=[('T', 'Thriller'), ('C', 'Comedy'), ('D', 'Drama'), ('ScI', 'Science-Fiction'), ('F', 'Fantasty'), ('H', 'Horror'), ('R', 'Romance')], max_length=3),
        ),
        migrations.AlterField(
            model_name='user_seats',
            name='ordered',
            field=models.DateTimeField(blank=True, default='2020-02-07 16:31', null=True),
        ),
    ]
