# Generated by Django 2.2.2 on 2020-01-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200118_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='age',
            field=models.CharField(choices=[('0', 'All'), ('16', 'Teenagers'), ('6', 'Kids'), ('21', 'Adults')], max_length=2),
        ),
        migrations.AlterField(
            model_name='movies',
            name='kind',
            field=models.CharField(choices=[('F', 'Fantasty'), ('T', 'Thriller'), ('D', 'Drama'), ('H', 'Horror'), ('R', 'Romance'), ('ScI', 'Science-Fiction'), ('C', 'Comedy')], max_length=3),
        ),
    ]
