# Generated by Django 2.2.2 on 2020-01-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200118_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='age',
            field=models.CharField(choices=[('16', 'Teenagers'), ('21', 'Adults'), ('0', 'All'), ('6', 'Kids')], max_length=2),
        ),
        migrations.AlterField(
            model_name='movies',
            name='kind',
            field=models.CharField(choices=[('F', 'Fantasty'), ('D', 'Drama'), ('H', 'Horror'), ('C', 'Comedy'), ('T', 'Thriller'), ('ScI', 'Science-Fiction'), ('R', 'Romance')], max_length=3),
        ),
    ]
