# Generated by Django 2.2.3 on 2020-03-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200207_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='cew',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='description',
        ),
        migrations.AlterField(
            model_name='movies',
            name='age',
            field=models.CharField(choices=[('6', 'Kids'), ('16', 'Teenagers'), ('21', 'Adults'), ('0', 'All')], max_length=2),
        ),
        migrations.AlterField(
            model_name='movies',
            name='kind',
            field=models.CharField(choices=[('D', 'Drama'), ('T', 'Thriller'), ('ScI', 'Science-Fiction'), ('F', 'Fantasty'), ('C', 'Comedy'), ('R', 'Romance'), ('H', 'Horror')], max_length=3),
        ),
        migrations.AlterField(
            model_name='user_seats',
            name='ordered',
            field=models.DateTimeField(blank=True, default='2020-03-03 14:19', null=True),
        ),
    ]
