# Generated by Django 2.2.3 on 2020-03-05 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20200303_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_seats',
            name='number',
        ),
        migrations.RemoveField(
            model_name='user_seats',
            name='row',
        ),
        migrations.AlterField(
            model_name='movies',
            name='age',
            field=models.CharField(choices=[('16', 'Teenagers'), ('0', 'All'), ('6', 'Kids'), ('21', 'Adults')], max_length=2),
        ),
        migrations.AlterField(
            model_name='movies',
            name='kind',
            field=models.CharField(choices=[('F', 'Fantasty'), ('T', 'Thriller'), ('ScI', 'Science-Fiction'), ('R', 'Romance'), ('C', 'Comedy'), ('D', 'Drama'), ('H', 'Horror')], max_length=3),
        ),
        migrations.AlterField(
            model_name='user_seats',
            name='ordered',
            field=models.DateTimeField(blank=True, default='2020-03-05 18:17', null=True),
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=1)),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user_seats',
            name='seats',
            field=models.ManyToManyField(to='main.Seats'),
        ),
    ]
