# Generated by Django 2.2.2 on 2020-01-18 22:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20200118_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='age',
            field=models.CharField(choices=[('0', 'All'), ('21', 'Adults'), ('16', 'Teenagers'), ('6', 'Kids')], max_length=2),
        ),
        migrations.AlterField(
            model_name='movies',
            name='kind',
            field=models.CharField(choices=[('R', 'Romance'), ('H', 'Horror'), ('C', 'Comedy'), ('ScI', 'Science-Fiction'), ('F', 'Fantasty'), ('T', 'Thriller'), ('D', 'Drama')], max_length=3),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=1)),
                ('number', models.IntegerField()),
                ('ordered', models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 18, 23, 14, 50, 453070), null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Movies')),
            ],
        ),
    ]
