# Generated by Django 2.2.2 on 2020-01-18 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200118_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='age',
            field=models.CharField(choices=[('16', 'Teenagers'), ('0', 'All'), ('21', 'Adults'), ('6', 'Kids')], max_length=2),
        ),
        migrations.AlterField(
            model_name='movies',
            name='kind',
            field=models.CharField(choices=[('H', 'Horror'), ('R', 'Romance'), ('T', 'Thriller'), ('ScI', 'Science-Fiction'), ('D', 'Drama'), ('F', 'Fantasty'), ('C', 'Comedy')], max_length=3),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='ordered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 18, 23, 15, 27, 723248), null=True),
        ),
    ]
