# Generated by Django 2.2.3 on 2020-03-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200305_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='age',
            field=models.CharField(choices=[('21', 'Adults'), ('0', 'All'), ('16', 'Teenagers'), ('6', 'Kids')], max_length=2),
        ),
        migrations.AlterField(
            model_name='movies',
            name='kind',
            field=models.CharField(choices=[('H', 'Horror'), ('F', 'Fantasty'), ('R', 'Romance'), ('ScI', 'Science-Fiction'), ('D', 'Drama'), ('C', 'Comedy'), ('T', 'Thriller')], max_length=3),
        ),
        migrations.AlterField(
            model_name='seats',
            name='ordered',
            field=models.DateTimeField(blank=True, default='2020-03-05 19:28', null=True),
        ),
        migrations.AlterField(
            model_name='user_seats',
            name='ordered',
            field=models.DateTimeField(blank=True, default='2020-03-05 19:28', null=True),
        ),
    ]
