# Generated by Django 2.2.2 on 2020-03-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200305_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dates',
            name='movie',
        ),
        migrations.AddField(
            model_name='dates',
            name='movies',
            field=models.ManyToManyField(to='main.Movies'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='age',
            field=models.CharField(choices=[('21', 'Adults'), ('16', 'Teenagers'), ('0', 'All'), ('6', 'Kids')], max_length=2),
        ),
        migrations.AlterField(
            model_name='movies',
            name='kind',
            field=models.CharField(choices=[('C', 'Comedy'), ('T', 'Thriller'), ('ScI', 'Science-Fiction'), ('H', 'Horror'), ('D', 'Drama'), ('F', 'Fantasty'), ('R', 'Romance')], max_length=3),
        ),
        migrations.AlterField(
            model_name='seats',
            name='ordered',
            field=models.DateTimeField(blank=True, default='2020-03-21 18:44', null=True),
        ),
        migrations.AlterField(
            model_name='user_seats',
            name='ordered',
            field=models.DateTimeField(blank=True, default='2020-03-21 18:44', null=True),
        ),
    ]
