# Generated by Django 2.2.2 on 2020-01-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200118_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='age',
            field=models.CharField(choices=[('16', 'Teenagers'), ('6', 'Kids'), ('21', 'Adults'), ('0', 'All')], max_length=2),
        ),
        migrations.AlterField(
            model_name='movies',
            name='kind',
            field=models.CharField(choices=[('C', 'Comedy'), ('ScI', 'Science-Fiction'), ('H', 'Horror'), ('R', 'Romance'), ('F', 'Fantasty'), ('T', 'Thriller'), ('D', 'Drama')], max_length=3),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='ordered',
            field=models.DateTimeField(blank=True, default='2020-01-18 23:48:$S', null=True),
        ),
    ]
