# Generated by Django 2.2.2 on 2020-03-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200321_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='dates',
            name='test',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movies',
            name='age',
            field=models.CharField(choices=[('6', 'Kids'), ('0', 'All'), ('16', 'Teenagers'), ('21', 'Adults')], max_length=2),
        ),
        migrations.AlterField(
            model_name='movies',
            name='kind',
            field=models.CharField(choices=[('H', 'Horror'), ('F', 'Fantasty'), ('R', 'Romance'), ('ScI', 'Science-Fiction'), ('T', 'Thriller'), ('C', 'Comedy'), ('D', 'Drama')], max_length=3),
        ),
        migrations.AlterField(
            model_name='seats',
            name='ordered',
            field=models.DateTimeField(blank=True, default='2020-03-21 18:50', null=True),
        ),
        migrations.AlterField(
            model_name='user_seats',
            name='ordered',
            field=models.DateTimeField(blank=True, default='2020-03-21 18:50', null=True),
        ),
    ]
