# Generated by Django 2.2.2 on 2020-01-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200118_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='age',
            field=models.CharField(choices=[('21', 'Adults'), ('16', 'Teenagers'), ('6', 'Kids'), ('0', 'All')], max_length=2),
        ),
        migrations.AlterField(
            model_name='movies',
            name='kind',
            field=models.CharField(choices=[('F', 'Fantasty'), ('ScI', 'Science-Fiction'), ('C', 'Comedy'), ('T', 'Thriller'), ('R', 'Romance'), ('D', 'Drama'), ('H', 'Horror')], max_length=3),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='ordered',
            field=models.DateTimeField(blank=True, default='2020-01-18 23:49:37', null=True),
        ),
    ]
