# Generated by Django 2.2.2 on 2020-03-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200321_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='age',
            field=models.CharField(choices=[('6', 'Kids'), ('16', 'Teenagers'), ('0', 'All'), ('21', 'Adults')], max_length=2),
        ),
        migrations.AlterField(
            model_name='movies',
            name='kind',
            field=models.CharField(choices=[('H', 'Horror'), ('C', 'Comedy'), ('D', 'Drama'), ('T', 'Thriller'), ('R', 'Romance'), ('F', 'Fantasty'), ('ScI', 'Science-Fiction')], max_length=3),
        ),
    ]
